<a href="https://colab.research.google.com/github/Haneen666/Machine-Learning-Models-Project/blob/main/%D8%A7%D9%84%D8%AA%D9%86%D8%A8%D8%A6_%D8%A8%D8%A7%D8%B3%D8%B9%D8%A7%D8%B1_%D8%A7%D9%84%D9%85%D9%86%D8%A7%D8%B2%D9%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()


Saving housepricedata.csv to housepricedata.csv


In [2]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv("housepricedata.csv")
data

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [4]:
data = pd.read_csv("housepricedata.csv").values
data

array([[ 8450,     7,     5, ...,     0,   548,     1],
       [ 9600,     6,     8, ...,     1,   460,     1],
       [11250,     7,     5, ...,     1,   608,     1],
       ...,
       [ 9042,     7,     9, ...,     2,   252,     1],
       [ 9717,     5,     6, ...,     0,   240,     0],
       [ 9937,     5,     6, ...,     0,   276,     0]])

In [5]:
x = data[:,0:10]
y = data[:,10]

In [6]:
print (x)
print (y)

[[ 8450     7     5 ...     8     0   548]
 [ 9600     6     8 ...     6     1   460]
 [11250     7     5 ...     6     1   608]
 ...
 [ 9042     7     9 ...     9     2   252]
 [ 9717     5     6 ...     5     0   240]
 [ 9937     5     6 ...     6     0   276]]
[1 1 1 ... 1 0 0]


In [7]:
x_train, x_val_and_test, y_train, y_val_and_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_val, x_test, y_val, y_test = train_test_split(x_val_and_test, y_val_and_test, test_size=0.5, random_state=42)

In [8]:
print (x_train)
print (y_train)

[[10400     7     6 ...     7     1   530]
 [ 3675     5     5 ...     5     0   525]
 [ 8640     7     5 ...     7     0   614]
 ...
 [ 8172     5     7 ...     5     0   572]
 [ 7642     7     8 ...     7     1   216]
 [ 3684     7     5 ...     7     1   660]]
[1 0 1 ... 0 1 1]


In [9]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_val=scaler.transform(x_val)

In [10]:
print (x_train)

[[-0.03050433  0.63603069  0.39226602 ...  0.27923396  0.59424033
   0.25381261]
 [-0.62436478 -0.82305655 -0.50862358 ... -0.94819445 -0.9432625
   0.22981353]
 [-0.18592357  0.63603069 -0.50862358 ...  0.27923396 -0.9432625
   0.65699721]
 ...
 [-0.22725096 -0.82305655  1.29315563 ... -0.94819445 -0.9432625
   0.45540491]
 [-0.27405334  0.63603069  2.19404524 ...  0.27923396  0.59424033
  -1.25332981]
 [-0.62357003  0.63603069 -0.50862358 ...  0.27923396  0.59424033
   0.87778877]]
